server:
  port: 8071
  servlet.contextPath: /

spring.data.elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: localhost:9300
  repositories.enabled: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
